### ISSUE TITLE
Makefile / Setup

### ISSUE THREAD

**Issue by cjlcarvalho** [sara-project/sara-documentation#2]
@IcaroJerry Poderia criar um makefile para automatizar essas tarefas de instalação, inicialização do schema e default data e para rodar, que tal?

**Comment by icarojerry** [comment]
Gostei da ideia, realmente facilitaria as coisas... Você pode submeter a mudança? 😃

**Comment by cjlcarvalho** [comment]
Posso sim. :)

**Comment by cjlcarvalho** [comment]
@IcaroJerry, fiz o PR lá no repositório. Dá uma olhada. https://github.com/S-A-R-A/sara-web/pull/2

**Comment by icarojerry** [comment]
Já aceitei o pull request, muito obrigado @cjlcarvalho! Fique a vontade para novas contribuições, kkk
